/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.UI;

import com.mycompany.psr.Cliente;
import java.awt.Button;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jorge
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    private Cliente cliente;

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();

        SwingUtilities.invokeLater(() -> {
            setButtonImageRescalable(btnPiedra, "/img/Piedra.png");
            setButtonImageRescalable(btnPapel, "/img/Papel.png");
            setButtonImageRescalable(btnTijera, "/img/Tijeras.png");
        });
        cliente = new Cliente();
        deshabilitarTodosBotones();
// Inicia un hilo para escuchar mensajes del servidor
        new Thread(() -> escucharServidor()).start();
    }

    private void escucharServidor() {
        try {
            boolean seguirJugando = true;
            while (seguirJugando) {
                String orden = cliente.recibirDato();
                if (orden.startsWith("Marcador:")) {
                    txtMarcador.setText(orden);
                    continue;
                }
                switch (orden) {
                    case "ELEGIR" -> {
                        // mostar los botones 
                        habilitarTexto(true);
                        habilitarBotones(true);
                        establecerTexto("Elige piedra, papel o tijera");
                    }
                    case "CONTINUAR" -> {
                        // ocultar botones y mostrar  los de elegir
                        establecerTexto("¿Quieres seguir jugando? (si/no)");
                        habilitarBotones(false);
                    }
                    case "FIN" -> {
                        mostrarMensaje("Fin de la partida. Gracias por jugar!");
                        deshabilitarTodosBotones();
                        seguirJugando = false;
                    }
                    case "SIGUIENTE" -> {
                        txtInfo.setText(" Nueva ronda");

                        btnPiedra.setVisible(true);
                        btnPapel.setVisible(true);
                        btnTijera.setVisible(true);
                        habilitarBotones(true);
                    }
                    default -> {

                        mostrarMensaje(orden);
                    }
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private void habilitarBotones(boolean estado) {
        btnPiedra.setVisible(estado);
        btnPapel.setVisible(estado);
        btnTijera.setVisible(estado);
        btnPiedra.setEnabled(true);
        btnPapel.setEnabled(true);
        btnTijera.setEnabled(true);
        //-------------
        btnNo.setVisible(!estado);
        btnSi.setVisible(!estado);
        btnSi.setEnabled(!estado);

    }

    private void habilitarTexto(boolean estado) {
        txtInfo.setVisible(estado);
    }

    private void deshabilitarTodosBotones() {
        btnPiedra.setVisible(false);
        btnPapel.setVisible(false);
        btnTijera.setVisible(false);
        //-------------
        txtInfo.setVisible(false);
        btnNo.setVisible(false);
        btnSi.setVisible(false);

    }

    private void botonSeleccionado(JButton botonSelecionado, String eleccion) {
        cliente.enviarDato(eleccion);
        btnPiedra.setVisible(false);
        btnPapel.setVisible(false);
        btnTijera.setVisible(false);
        botonSelecionado.setVisible(true);
        botonSelecionado.setEnabled(false);

        establecerTexto("Has elegico " + eleccion + " , esperando al otro jugador...");
    }

    private void establecerTexto(String mensaje) {
        txtInfo.setText(mensaje);
    }

    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPiedra = new javax.swing.JButton();
        btnPapel = new javax.swing.JButton();
        btnTijera = new javax.swing.JButton();
        txtInfo = new javax.swing.JLabel();
        btnNo = new javax.swing.JButton();
        btnSi = new javax.swing.JButton();
        txtMarcador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiedraActionPerformed(evt);
            }
        });

        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btnTijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTijeraActionPerformed(evt);
            }
        });

        txtInfo.setText("accion a relizar");

        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        btnSi.setText("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        txtMarcador.setText("Marcador: 0 - 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTijera, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtInfo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(txtMarcador)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(157, Short.MAX_VALUE)
                    .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(84, 84, 84)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txtMarcador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(txtInfo)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTijera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(190, 190, 190))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(251, Short.MAX_VALUE)
                    .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(207, 207, 207)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(253, 253, 253)
                    .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
        cliente.enviarDato("no");
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // TODO add your handling code here:
        cliente.enviarDato("si");
        deshabilitarTodosBotones();
        btnSi.setVisible(true);
        btnSi.setEnabled(false);
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnTijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTijeraActionPerformed
        // TODO add your handling code here:
        botonSeleccionado(btnTijera, "tijera");

    }//GEN-LAST:event_btnTijeraActionPerformed

    private void btnPiedraActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        botonSeleccionado(btnPiedra, "piedra");

    }

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        botonSeleccionado(btnPapel, "papel");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }

        });
    }

    private void setButtonImageRescalable(JButton button, String resourcePath) {
        // Obtenemos la URL del recurso
        java.net.URL imgURL = getClass().getResource(resourcePath);

        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            Image image = icon.getImage().getScaledInstance(
                    80,
                    80,
                    Image.SCALE_SMOOTH);
            button.setIcon(new ImageIcon(image));
        } else {
            System.err.println("Error: No se pudo encontrar el archivo en " + resourcePath);
        }

        // hacer el boton trasparente:
        button.setBorderPainted(false);
        button.setContentAreaFilled(false); // Quita el fondo gris/blanco
        button.setFocusPainted(false);      // Quita el borde de selección
        button.setOpaque(false);            // Asegura transparencia
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnPiedra;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton btnTijera;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtMarcador;
    // End of variables declaration//GEN-END:variables
}
